CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migrationid character varying(150) NOT NULL,
    productversion character varying(32) NOT NULL,
    CONSTRAINT pk___efmigrationshistory PRIMARY KEY (migrationid)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'article') THEN
        CREATE SCHEMA article;
    END IF;
END $EF$;

CREATE TABLE article."AspNetRoles" (
    id text NOT NULL,
    name character varying(256),
    normalizedname character varying(256),
    concurrencystamp text,
    CONSTRAINT pk_aspnetroles PRIMARY KEY (id)
);

CREATE TABLE article."AspNetUsers" (
    id text NOT NULL,
    email character varying(256) NOT NULL,
    password text NOT NULL,
    username character varying(256),
    normalizedusername character varying(256),
    normalizedemail character varying(256),
    emailconfirmed boolean NOT NULL,
    passwordhash text,
    securitystamp text,
    concurrencystamp text,
    phonenumber text,
    phonenumberconfirmed boolean NOT NULL,
    twofactorenabled boolean NOT NULL,
    lockoutend timestamp with time zone,
    lockoutenabled boolean NOT NULL,
    accessfailedcount integer NOT NULL,
    CONSTRAINT pk_aspnetusers PRIMARY KEY (id)
);

CREATE TABLE article.identityuser (
    id text NOT NULL,
    username text,
    normalizedusername text,
    email text,
    normalizedemail text,
    emailconfirmed boolean NOT NULL,
    passwordhash text,
    securitystamp text,
    concurrencystamp text,
    phonenumber text,
    phonenumberconfirmed boolean NOT NULL,
    twofactorenabled boolean NOT NULL,
    lockoutend timestamp with time zone,
    lockoutenabled boolean NOT NULL,
    accessfailedcount integer NOT NULL,
    CONSTRAINT pk_identityuser PRIMARY KEY (id)
);

CREATE TABLE article."AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    roleid text NOT NULL,
    claimtype text,
    claimvalue text,
    CONSTRAINT pk_aspnetroleclaims PRIMARY KEY (id),
    CONSTRAINT fk_aspnetroleclaims_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES article."AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE article."AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid text NOT NULL,
    claimtype text,
    claimvalue text,
    CONSTRAINT pk_aspnetuserclaims PRIMARY KEY (id),
    CONSTRAINT fk_aspnetuserclaims_aspnetusers_userid FOREIGN KEY (userid) REFERENCES article."AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE article."AspNetUserLogins" (
    loginprovider text NOT NULL,
    providerkey text NOT NULL,
    providerdisplayname text,
    userid text NOT NULL,
    CONSTRAINT pk_aspnetuserlogins PRIMARY KEY (loginprovider, providerkey),
    CONSTRAINT fk_aspnetuserlogins_aspnetusers_userid FOREIGN KEY (userid) REFERENCES article."AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE article."AspNetUserRoles" (
    userid text NOT NULL,
    roleid text NOT NULL,
    CONSTRAINT pk_aspnetuserroles PRIMARY KEY (userid, roleid),
    CONSTRAINT fk_aspnetuserroles_aspnetroles_roleid FOREIGN KEY (roleid) REFERENCES article."AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT fk_aspnetuserroles_aspnetusers_userid FOREIGN KEY (userid) REFERENCES article."AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE article."AspNetUserTokens" (
    userid text NOT NULL,
    loginprovider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_aspnetusertokens PRIMARY KEY (userid, loginprovider, name),
    CONSTRAINT fk_aspnetusertokens_aspnetusers_userid FOREIGN KEY (userid) REFERENCES article."AspNetUsers" (id) ON DELETE CASCADE
);

INSERT INTO article.identityuser (id, accessfailedcount, concurrencystamp, email, emailconfirmed, lockoutenabled, lockoutend, normalizedemail, normalizedusername, passwordhash, phonenumber, phonenumberconfirmed, securitystamp, twofactorenabled, username)
VALUES ('default-user-id', 0, '31612c96-79c3-46da-a214-c7897ca5406d', 'default@example.com', FALSE, TRUE, NULL, 'DEFAULT@EXAMPLE.COM', 'DEFAULT@EXAMPLE.COM', 'AQAAAAIAAYagAAAAEIu3JP+1HmCZcWtZvRpobAxOTnCQ5SxMPuWCh4SrG2yrg3qcgV5YYLzVwFr/Z5i6BQ==', NULL, FALSE, 'c8205be7-e853-4796-9552-75e5c6bd962d', FALSE, 'default@example.com');

CREATE INDEX ix_aspnetroleclaims_roleid ON article."AspNetRoleClaims" (roleid);

CREATE UNIQUE INDEX "RoleNameIndex" ON article."AspNetRoles" (normalizedname);

CREATE INDEX ix_aspnetuserclaims_userid ON article."AspNetUserClaims" (userid);

CREATE INDEX ix_aspnetuserlogins_userid ON article."AspNetUserLogins" (userid);

CREATE INDEX ix_aspnetuserroles_roleid ON article."AspNetUserRoles" (roleid);

CREATE INDEX "EmailIndex" ON article."AspNetUsers" (normalizedemail);

CREATE UNIQUE INDEX "UserNameIndex" ON article."AspNetUsers" (normalizedusername);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20240725211738_abc', '8.0.7');

COMMIT;

